name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install replace utility
        run: npm install -g replace

      - name: Replace Firebase configuration
        run: |
          replace "FIREBASE_API_KEY" "${{ secrets.FIREBASE_API_KEY }}" scripts/firebase-config.js
          replace "FIREBASE_AUTH_DOMAIN" "${{ secrets.FIREBASE_AUTH_DOMAIN }}" scripts/firebase-config.js
          replace "FIREBASE_PROJECT_ID" "${{ secrets.FIREBASE_PROJECT_ID }}" scripts/firebase-config.js
          replace "FIREBASE_STORAGE_BUCKET" "${{ secrets.FIREBASE_STORAGE_BUCKET }}" scripts/firebase-config.js
          replace "FIREBASE_MESSAGING_SENDER_ID" "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" scripts/firebase-config.js
          replace "FIREBASE_APP_ID" "${{ secrets.FIREBASE_APP_ID }}" scripts/firebase-config.js
          replace "FIREBASE_MEASUREMENT_ID" "${{ secrets.FIREBASE_MEASUREMENT_ID }}" scripts/firebase-config.js

      - name: Replace Ideris Private Key
        run: |
          replace "IDERIS_PRIVATE_KEY" "${{ secrets.IDERIS_PRIVATE_KEY }}" scripts/app.js

      - name: Verify replacements
        run: |
          echo "=== Verificando substituições ==="
          
          # Verificar Firebase
          if grep -q "FIREBASE_API_KEY" scripts/firebase-config.js; then
            echo "❌ ERRO: Firebase API Key não foi substituída!"
            exit 1
          else
            echo "✅ Firebase API Key substituída com sucesso"
          fi
          
          # Verificar Ideris
          if grep -q "IDERIS_PRIVATE_KEY" scripts/app.js; then
            echo "❌ ERRO: Ideris Private Key não foi substituída!"
            exit 1
          else
            echo "✅ Ideris Private Key substituída com sucesso"
          fi
          
          echo "=== Todas as substituições verificadas ==="

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: .

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
